---
- hosts: mywebservers
  become: yes
  gather_facts: yes
  tasks: 
  - name: i want to install java on ubuntu
    apt:
      name: "{{mywebpackforubuntu}}"
      state: present
    when: ansible_os_family=="Debian"  

  - name: i want to install java on RedHat
    yum:
      name: "{{mywebpackforredhat}}"
      state: present
    when: ansible_os_family=="Redhat"    