---
- hosts: 172.31.29.153
  become: yes
  tasks:
  - include_tasks: myfile.yml

  - name: i want to install webserver
    apt:
      name: apache2
      state: present

  - name: i want to copy indexfile into ansible node
    template:
      src: myindexfile.j2
      dest: /var/www/html/index.html
  
