---
- hosts: mywebservers
  become: yes
  gather_facts: yes
  tasks: 
  - name: i want to install webserver on ubuntu ansible node
    apt: 
      name: "{{mywebpackforubuntu}}"
      state: present
    when: ansible_os_family=="Debian"

  - name: i want to start webserver on ansible ubuntu node
    service:
      name: "{{mywebpackforubuntu}}"
      state: started  
    when: ansible_os_family=="Debian"

  - name: i want to install webserver on RedHat ansible node
    yum:
      name: "{{mywebpackforredhat}}"
      state: present
    when: ansible_os_family=="RedHat"

  - name: i want to start webserver on ansible RedHat node
    service:
      name: "{{mywebpackforredhat}}"
      state: started  
    when: ansible_os_family=="RedHat"
