---
- name: copy tomcat usefr file into node side
  template: 
      src: templates/webmgmt.j2
      dest: /opt/tomcat/conf/tomcat-users.xml

- name: tomcat context file
  template: 
      src: templates/contextfile.j2
      dest: /opt/tomcat/webapps/manager/META-INF/context.xml

- name: tomcat host context file
  template: 
      src: templates/hostcontextfile.j2
      dest: /opt/tomcat/webapps/host-manager/META-INF/context.xml